alter table ROYALDIARY_FARMER add constraint FK_ROYALDIARY_FARMER_ADDRESS foreign key (ADDRESS_ID) references ROYALDIARY_ADDRESS(ID);
create index IDX_ROYALDIARY_FARMER_ADDRESS on ROYALDIARY_FARMER (ADDRESS_ID);
