alter table ROYALDIARY_FARMER_ADDRESS alter column FARMER_ID_ID rename to FARMER_ID_ID__U29232 ;
drop index IDX_ROYALDIARY_FARMER_ADDRESS_FARMER_ID ;
alter table ROYALDIARY_FARMER_ADDRESS drop constraint FK_ROYALDIARY_FARMER_ADDRESS_FARMER_ID ;
alter table ROYALDIARY_FARMER_ADDRESS add column FARMER_ID varchar(36) ;
